import IconAll from "@/assets/svg/icon-all.svg"
import IconPhone from "@/assets/svg/icon-phone.svg"
import IconBrain from "@/assets/svg/icon-brain.svg"
import IconHome from "@/assets/svg/icon-home.svg"
import IconTask from "@/assets/svg/icon-task.svg"
import IconNavigation from "@/assets/svg/icon-navigation.svg"
import IconHeadset from "@/assets/svg/icon-headset.svg"
import IconMovies from "@/assets/svg/icon-movies.svg"
import IconSports from "@/assets/svg/icon-sports.svg"
import type { SiriDoesAll } from "@/types/SiriDoesAll"

export const SIRI_DOES_ALL: SiriDoesAll[] = [
    {
        image: {
            icon: IconAll,
            width: 44,
            height: 29
        },
        dataId: "all",
        category: "All",
        allText: [],
        color: 'linear-gradient(#152046, #152046) padding-box, linear-gradient(to bottom right, #D400A5, #1E76C9, #35FCED) border-box;'
    },
    {
        image: {
            icon: IconPhone,
            width: 19,
            height: 32
        },
        dataId: "calls-and-texts",
        category: "Calls and Texts",
        color: '#D03587',
        texts: [
            "Hey Siri, answer the phone",
            "Hey Siri, FaceTime Henri",
            "Hey Siri, message Vivek on WhatsApp, ‘Where do you want to meet?’",
            "Hey Siri, read my last text from Bob",
            "Hey Siri, what’s my brother’s work address?",
            "Siri, text Josh, ‘How do you feel about sushi tonight?’",
            "Hey Siri, answer the phone",
            "Hey Siri, FaceTime Henri",
            "Hey Siri, message Vivek on WhatsApp, ‘Where do you want to meet?’",
            "Hey Siri, read my last text from Bob",
            "Siri, text Mom my location",
            "Siri, call Oren’s Hummus",
            "Siri, call Eliza",
            "Siri, FaceTime Family group chat",
            "Siri, share this with Lauren",
            "Siri, play my voicemails",
            "Siri, text Mom my location",
            "Siri, call Oren’s Hummus",
            "Siri, call Eliza",
            "Siri, FaceTime Family group chat",
            "Siri, tell Nisha I’ll be home in 15 minutes",
            "Siri, return my last call",
            "Siri, call Mom on speaker",
            "Siri, who’s calling?",
            "Siri, hang up",
            "Siri, tell Nisha I’ll be home in 15 minutes",
            "Siri, return my last call",
            "Siri, call Mom on speaker",
            "Siri, who’s calling?",
            "Siri, hang up"
        ]
    },
    {
        image: {
            icon: IconBrain,
            width: 33,
            height: 41
        },
        dataId: "knowledge-and-answers",
        category: "Knowledge and Answers",
        color: '#F97659',
        texts: [
            "Hey Siri, how windy is it?",
            "Hey Siri, what can I ask you?",
            "Hey Siri, what's 74 times 9?",
            "Hey Siri, how do you say 'I love you' in French?",
            "Hey Siri, define 'happenstance'",
            "Siri, what's in a Gin Rickey?",
            "Hey Siri, how windy is it?",
            "Hey Siri, what can I ask you?",
            "Hey Siri, what's 74 times 9?",
            "Hey Siri, how do you say 'I love you' in French?",
            "Siri, what causes a rainbow?",
            "Siri, how's the stock market doing?",
            "Siri, what's tomorrow's forecast for Honolulu?",
            "Siri, what's 20% of $184?",
            "Siri, how do you spell 'fuchsia'?",
            "Siri, how old is Olivia Rodrigo?",
            "Siri, what causes a rainbow?",
            "Siri, how's the stock market doing?",
            "Siri, what's tomorrow's forecast for Honolulu?",
            "Siri, what's 20% of $184?",
            "Siri, what time is it in Stockholm?",
            "Siri, what's the news today?",
            "Hey Siri, how many dollars is 45 euros?",
            "Siri, what is the population of Toronto?",
            "Siri, what time is it in Stockholm?",
            "Siri, what's the news today?",
            "Hey Siri, how many dollars is 45 euros?",
            "Siri, what is the population of Toronto?",
            "Siri, who's calling?",
            "Siri, hang up"
        ]
    },
    {
        image: {
            icon: IconHome,
            width: 44,
            height: 40
        },
        dataId: "smart-home",
        category: "Smart Home",
        color: '#4DA3F9',
        texts: [
            'Hey Siri, turn on the lights',
            'Hey Siri, set the temperature to 72 degrees',
            'Hey Siri, arm the security system',
            'Hey Siri, are the upstairs lights on?',
            'Hey Siri, play a song I like in the kitchen',
            'Siri, turn on the living room TV',
            'Hey Siri, turn on the lights',
            'Hey Siri, set the temperature to 72 degrees',
            'Hey Siri, arm the security system',
            'Hey Siri, are the upstairs lights on?',
            'Siri, turn off the TV when I leave',
            'Siri, open the blinds at 7 AM',
            'Siri, turn on the fan in the living room and kitchen',
            'Siri, intercom, ‘Time for school’',
            'Siri, turn the patio lights off in an hour',
            'Siri, make it cooler',
            'Siri, turn off the TV when I leave',
            'Siri, open the blinds at 7 AM',
            'Siri, turn on the fan in the living room and kitchen',
            'Siri, intercom, ‘Time for school’',
            'Siri, it’s movie night',
            'Siri, announce, ‘On my way home, want me to pick anything up?’',
            'Siri, is the front door locked?',
            'Siri, I’m home',
            'Siri, did I close the garage door?',
            'Siri, show driveway camera',
            'Siri, it’s movie night',
            'Siri, announce, ‘On my way home, want me to pick anything up?’',
            'Siri, is the front door locked?',
            'Siri, I’m home'
        ]
    },
    {
        image: {
            icon: IconTask,
            width: 37,
            height: 34
        },
        dataId: "everyday-tasks",
        category: "Everyday Tasks",
        color: '#10A48A',
        texts: [
            "Hey Siri, open Photos",
            "Hey Siri, turn on Do Not Disturb",
            "Hey Siri, scan a QR code",
            "Hey Siri, open Camera",
            "Hey Siri, find my iPhone",
            "Siri, ping my iPad",
            "Hey Siri, open Photos",
            "Hey Siri, turn on Do Not Disturb",
            "Hey Siri, scan a QR code",
            "Hey Siri, open Camera",
            "Siri, where are my keys?",
            "Siri, remind me to email Kate when I get to work",
            "Siri, where is Julie?",
            "Siri, Apple Pay $75 to Phillip",
            "Siri, split a $213 check three ways",
            "Siri, what time is my first meeting tomorrow?",
            "Siri, where are my keys?",
            "Siri, remind me to email Kate when I get to work",
            "Siri, where is Julie?",
            "Siri, Apple Pay $75 to Phillip",
            "Siri, what’s on my calendar for today?",
            "Siri, add eggs to my grocery list",
            "Siri, remind me to buy coffee",
            "Siri, open Voice Memos",
            "Siri, turn on Flashlight",
            "Siri, start a yoga workout on Apple Fitness+",
            "Siri, what’s on my calendar for today?",
            "Siri, add eggs to my grocery list",
            "Siri, remind me to buy coffee",
            "Siri, open Voice Memos"
        ]
    },
    {
        image: {
            icon: IconNavigation,
            width: 34,
            height: 34
        },
        dataId: "navigation-and-maps",
        category: "Navigation and Maps",
        color: '#F43F55',
        texts: [
            "Hey Siri, get directions to Home Depot",
            "Hey Siri, what time does Philz Coffee open?",
            "Hey Siri, find a gas station",
            "Hey Siri, what’s my ETA?",
            "Hey Siri, how’s the traffic to work today?",
            "Hey Siri, get directions to Home Depot",
            "Hey Siri, what time does Philz Coffee open?",
            "Hey Siri, find a gas station",
            "Hey Siri, what’s my ETA?",
            "Hey Siri, how’s the traffic to work today?",
            "Siri, find coffee shops that take Apple Pay",
            "Siri, where am I?",
            "Siri, convenience stores open now",
            "Siri, find a hiking trail nearby",
            "Siri, transit directions to the Ferry Building",
            "Siri, find coffee shops that take Apple Pay",
            "Siri, where am I?",
            "Siri, convenience stores open now",
            "Siri, find a hiking trail nearby",
            "Siri, transit directions to the Ferry Building",
            "Siri, biking directions to Golden Gate Park",
            "Siri, open Maps",
            "Siri, how long will it take to get home?",
            "Siri, show me the map",
            "Siri, stop navigating",
            "Siri, biking directions to Golden Gate Park",
            "Siri, open Maps",
            "Siri, how long will it take to get home?",
            "Siri, show me the map",
            "Siri, stop navigating"
        ]
    },
    {
        image: {
            icon: IconHeadset,
            width: 34,
            height: 35
        },
        dataId: "music-and-podcasts",
        category: "Music and Podcasts",
        color: "#804EFE",
        texts: [
            "Hey Siri, play something I can dance to",
            "Hey Siri, what song is this?",
            "Hey Siri, play Charli XCX",
            "Hey Siri, play more like this",
            "Hey Siri, play my personal music station",
            "Hey Siri, play something I can dance to",
            "Hey Siri, what song is this?",
            "Hey Siri, play Charli XCX",
            "Hey Siri, play more like this",
            "Hey Siri, play my personal music station",
            "Siri, play The Weeknd on Pandora",
            "Siri, who sings this song?",
            "Siri, play Planet Money",
            "Siri, play Radiolab on Overcast",
            "Siri, play this podcast twice as fast",
            "Siri, play The Weeknd on Pandora",
            "Siri, who sings this song?",
            "Siri, play Planet Money",
            "Siri, play Radiolab on Overcast",
            "Siri, play this podcast twice as fast",
            "Siri, play something chill",
            "Siri, skip forward 30 seconds",
            "Siri, I like this song",
            "Siri, add this song to my workout playlist",
            "Siri, Shazam this song",
            "Siri, play something chill",
            "Siri, skip forward 30 seconds",
            "Siri, I like this song",
            "Siri, add this song to my workout playlist",
            "Siri, Shazam this song"
        ]
    },
    {
        image: {
            icon: IconMovies,
            width: 39,
            height: 32
        },
        dataId: "tv-and-movies",
        category: "TV and Movies",
        color: '#AE5FFE', 
        texts: [
            "Hey Siri, watch Ted Lasso on Apple TV",
            "Hey Siri, open Netflix",
            "Hey Siri, puppy videos",
            "Hey Siri, what movies are playing at Landmark Theatres?",
            "Hey Siri, what is the movie Trolls World Tour rated?",
            "Hey Siri, watch Ted Lasso on Apple TV",
            "Hey Siri, open Netflix",
            "Hey Siri, puppy videos",
            "Hey Siri, what movies are playing at Landmark Theatres?",
            "Hey Siri, what is the movie Trolls World Tour rated?",
            "Siri, what did she say?",
            "Siri, turn on subtitles",
            "Siri, find movies starring Anne Hathaway",
            "Siri, find romantic comedy movies",
            "Siri, who directed this movie?",
            "Siri, what did she say?",
            "Siri, turn on subtitles",
            "Siri, find movies starring Anne Hathaway",
            "Siri, find romantic comedy movies",
            "Siri, who directed this movie?",
            "Siri, kid-friendly movies",
            "Siri, play Physical Season 1, Episode 3",
            "Siri, pause the living room TV",
            "Siri, how are the reviews for Tenet?",
            "Siri, watch His Dark Materials",
            "Siri, kid-friendly movies",
            "Siri, play Physical Season 1, Episode 3",
            "Siri, pause the living room TV",
            "Siri, how are the reviews for Tenet?",
            "Siri, watch His Dark Materials"
        ]
    },
    {
        image: {
            icon: IconSports,
            width: 55,
            height: 32
        },
        dataId: "sports",
        category: "Sports",
        color: '#3D53FF',
        texts: [
            "Hey Siri, Vegas Golden Knights score",
            "Hey Siri, San Jose Sharks roster",
            "Hey Siri, who has the most home runs in baseball?",
            "Hey Siri, college football rankings",
            "Hey Siri, which quarterback has the most passing yards?",
            "Hey Siri, what NFL games are on?",
            "Hey Siri, Vegas Golden Knights score",
            "Hey Siri, San Jose Sharks roster",
            "Hey Siri, who has the most home runs in baseball?",
            "Hey Siri, college football rankings",
            "Siri, who has the most goals in Major League Soccer?",
            "Siri, what schools are in the Big Ten?",
            "Siri, what conference is the University of Kentucky in?",
            "Siri, who is pitching for Detroit this season?",
            "Siri, how many points did Sabrina Ionescu score last game?",
            "Siri, what’s tonight’s NBA schedule?",
            "Siri, who has the most goals in Major League Soccer?",
            "Siri, what schools are in the Big Ten?",
            "Siri, what conference is the University of Kentucky in?",
            "Siri, who is pitching for Detroit this season?",
            "Siri, next Eagles game",
            "Siri, who’s playing baseball tonight?",
            "Siri, who’s the tallest professional basketball player?",
            "Siri, what NHL games are on?",
            "Siri, next Eagles game",
            "Siri, who’s playing baseball tonight?",
            "Siri, who’s the tallest professional basketball player?",
            "Siri, what NHL games are on?",
            "Siri, how are the reviews for Tenet?",
            "Siri, watch His Dark Materials"
        ]
    }
]